# Generated by Django 2.2.6 on 2019-10-17 19:42

import address.models
from django.db import migrations
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191017_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
