# Generated by Django 2.2.6 on 2019-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191017_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_address',
            field=models.CharField(max_length=100),
        ),
    ]
